import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Gift, 
  Users,
  User,
  DollarSign,
  Settings,
  TrendingUp,
  Target,
  Truck,
  CheckCircle,
  Clock,
  Zap,
} from 'lucide-react';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { toast } from 'sonner';

// Types
interface BonusConfig {
  id: string;
  type: 'META_PERSONAL' | 'META_EQUIPO' | 'VIAJE';
  name: string;
  description: string;
  amount: number;
  threshold: number; // Meta a alcanzar (ventas, % de cumplimiento, etc.)
  thresholdUnit: string; // 'soles', '%', 'viajes'
  isActive: boolean;
}

interface AutoBonus {
  id: string;
  configId: string;
  type: 'META_PERSONAL' | 'META_EQUIPO' | 'VIAJE';
  name: string;
  amount: number;
  employeeId?: string;
  employeeName?: string;
  teamName?: string;
  achievedValue: number;
  threshold: number;
  thresholdUnit: string;
  date: Date;
  status: 'GENERADO' | 'APROBADO' | 'PAGADO';
}

// Mock configurations
const initialBonusConfigs: BonusConfig[] = [
  {
    id: 'config-1',
    type: 'META_PERSONAL',
    name: 'Bono por Meta de Ventas Personal',
    description: 'Se otorga cuando el vendedor alcanza su meta mensual de ventas',
    amount: 200,
    threshold: 10000,
    thresholdUnit: 'soles',
    isActive: true,
  },
  {
    id: 'config-2',
    type: 'META_PERSONAL',
    name: 'Bono por Superar Meta 150%',
    description: 'Bono adicional por superar la meta en 150%',
    amount: 500,
    threshold: 150,
    thresholdUnit: '%',
    isActive: true,
  },
  {
    id: 'config-3',
    type: 'META_EQUIPO',
    name: 'Bono por Meta de Equipo',
    description: 'Se otorga cuando el equipo alcanza la meta grupal',
    amount: 150,
    threshold: 50000,
    thresholdUnit: 'soles',
    isActive: true,
  },
  {
    id: 'config-4',
    type: 'VIAJE',
    name: 'Bono por Viaje Completado',
    description: 'Se otorga por cada viaje de reparto completado exitosamente',
    amount: 25,
    threshold: 1,
    thresholdUnit: 'viajes',
    isActive: true,
  },
  {
    id: 'config-5',
    type: 'VIAJE',
    name: 'Bono por 10 Viajes Semanales',
    description: 'Bono especial al completar 10 viajes en una semana',
    amount: 100,
    threshold: 10,
    thresholdUnit: 'viajes',
    isActive: true,
  },
];

// Mock auto-generated bonuses (these would be generated by the system)
const initialAutoBonuses: AutoBonus[] = [
  {
    id: 'auto-001',
    configId: 'config-1',
    type: 'META_PERSONAL',
    name: 'Bono por Meta de Ventas Personal',
    amount: 200,
    employeeId: 'seller-1',
    employeeName: 'Pedro García',
    achievedValue: 12500,
    threshold: 10000,
    thresholdUnit: 'soles',
    date: new Date(),
    status: 'GENERADO',
  },
  {
    id: 'auto-002',
    configId: 'config-2',
    type: 'META_PERSONAL',
    name: 'Bono por Superar Meta 150%',
    amount: 500,
    employeeId: 'seller-1',
    employeeName: 'Pedro García',
    achievedValue: 160,
    threshold: 150,
    thresholdUnit: '%',
    date: new Date(),
    status: 'APROBADO',
  },
  {
    id: 'auto-003',
    configId: 'config-3',
    type: 'META_EQUIPO',
    name: 'Bono por Meta de Equipo',
    amount: 150,
    teamName: 'Equipo Vendedores',
    achievedValue: 52000,
    threshold: 50000,
    thresholdUnit: 'soles',
    date: new Date(),
    status: 'PAGADO',
  },
  {
    id: 'auto-004',
    configId: 'config-4',
    type: 'VIAJE',
    name: 'Bono por Viaje Completado',
    amount: 25,
    employeeId: 'driver-1',
    employeeName: 'Carlos Ramos',
    achievedValue: 1,
    threshold: 1,
    thresholdUnit: 'viajes',
    date: new Date(Date.now() - 86400000),
    status: 'PAGADO',
  },
  {
    id: 'auto-005',
    configId: 'config-5',
    type: 'VIAJE',
    name: 'Bono por 10 Viajes Semanales',
    amount: 100,
    employeeId: 'driver-1',
    employeeName: 'Carlos Ramos',
    achievedValue: 12,
    threshold: 10,
    thresholdUnit: 'viajes',
    date: new Date(),
    status: 'GENERADO',
  },
  {
    id: 'auto-006',
    configId: 'config-1',
    type: 'META_PERSONAL',
    name: 'Bono por Meta de Ventas Personal',
    amount: 200,
    employeeId: 'seller-2',
    employeeName: 'Luis Mendoza',
    achievedValue: 11200,
    threshold: 10000,
    thresholdUnit: 'soles',
    date: new Date(Date.now() - 172800000),
    status: 'APROBADO',
  },
];

const EmployeeBonuses = () => {
  const [bonusConfigs, setBonusConfigs] = useState<BonusConfig[]>(initialBonusConfigs);
  const [autoBonuses, setAutoBonuses] = useState<AutoBonus[]>(initialAutoBonuses);
  const [isConfigDialogOpen, setIsConfigDialogOpen] = useState(false);
  const [editingConfig, setEditingConfig] = useState<BonusConfig | null>(null);
  const [typeFilter, setTypeFilter] = useState<string>('all');
  const [activeTab, setActiveTab] = useState('bonuses');

  // Form state for editing config
  const [configForm, setConfigForm] = useState({
    name: '',
    description: '',
    amount: '',
    threshold: '',
    thresholdUnit: 'soles',
    type: 'META_PERSONAL' as BonusConfig['type'],
  });

  const filteredBonuses = autoBonuses.filter(bonus => 
    typeFilter === 'all' || bonus.type === typeFilter
  );

  const stats = {
    totalBonuses: autoBonuses.length,
    pendingBonuses: autoBonuses.filter(b => b.status === 'GENERADO').length,
    approvedBonuses: autoBonuses.filter(b => b.status === 'APROBADO').length,
    totalAmount: autoBonuses.reduce((sum, b) => sum + b.amount, 0),
    activeConfigs: bonusConfigs.filter(c => c.isActive).length,
  };

  const handleEditConfig = (config: BonusConfig) => {
    setEditingConfig(config);
    setConfigForm({
      name: config.name,
      description: config.description,
      amount: config.amount.toString(),
      threshold: config.threshold.toString(),
      thresholdUnit: config.thresholdUnit,
      type: config.type,
    });
    setIsConfigDialogOpen(true);
  };

  const handleSaveConfig = () => {
    if (!configForm.name || !configForm.amount || !configForm.threshold) {
      toast.error('Complete los campos requeridos');
      return;
    }

    if (editingConfig) {
      setBonusConfigs(prev => prev.map(config => 
        config.id === editingConfig.id 
          ? {
              ...config,
              name: configForm.name,
              description: configForm.description,
              amount: parseFloat(configForm.amount),
              threshold: parseFloat(configForm.threshold),
              thresholdUnit: configForm.thresholdUnit,
            }
          : config
      ));
      toast.success('Configuración actualizada');
    } else {
      const newConfig: BonusConfig = {
        id: `config-${Date.now()}`,
        type: configForm.type,
        name: configForm.name,
        description: configForm.description,
        amount: parseFloat(configForm.amount),
        threshold: parseFloat(configForm.threshold),
        thresholdUnit: configForm.thresholdUnit,
        isActive: true,
      };
      setBonusConfigs(prev => [...prev, newConfig]);
      toast.success('Nueva configuración creada');
    }

    setIsConfigDialogOpen(false);
    setEditingConfig(null);
    resetConfigForm();
  };

  const resetConfigForm = () => {
    setConfigForm({
      name: '',
      description: '',
      amount: '',
      threshold: '',
      thresholdUnit: 'soles',
      type: 'META_PERSONAL',
    });
  };

  const handleToggleConfig = (configId: string) => {
    setBonusConfigs(prev => prev.map(config =>
      config.id === configId 
        ? { ...config, isActive: !config.isActive }
        : config
    ));
    toast.success('Estado actualizado');
  };

  const handleApproveBonus = (bonusId: string) => {
    setAutoBonuses(prev => prev.map(bonus =>
      bonus.id === bonusId 
        ? { ...bonus, status: 'APROBADO' as const }
        : bonus
    ));
    toast.success('Bono aprobado');
  };

  const handlePayBonus = (bonusId: string) => {
    setAutoBonuses(prev => prev.map(bonus =>
      bonus.id === bonusId 
        ? { ...bonus, status: 'PAGADO' as const }
        : bonus
    ));
    toast.success('Bono marcado como pagado');
  };

  const getStatusBadge = (status: AutoBonus['status']) => {
    const styles = {
      GENERADO: 'bg-warning/10 text-warning border-warning/20',
      APROBADO: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
      PAGADO: 'bg-success/10 text-success border-success/20',
    };
    const icons = {
      GENERADO: <Clock className="h-3 w-3 mr-1" />,
      APROBADO: <CheckCircle className="h-3 w-3 mr-1" />,
      PAGADO: <DollarSign className="h-3 w-3 mr-1" />,
    };
    return (
      <Badge variant="outline" className={`${styles[status]} flex items-center`}>
        {icons[status]}
        {status}
      </Badge>
    );
  };

  const getTypeBadge = (type: AutoBonus['type']) => {
    const config = {
      META_PERSONAL: { icon: User, label: 'Meta Personal', className: 'bg-blue-500/10 text-blue-500' },
      META_EQUIPO: { icon: Users, label: 'Meta Equipo', className: 'bg-purple-500/10 text-purple-500' },
      VIAJE: { icon: Truck, label: 'Por Viaje', className: 'bg-orange-500/10 text-orange-500' },
    };
    const { icon: Icon, label, className } = config[type];
    return (
      <Badge variant="secondary" className={className}>
        <Icon className="h-3 w-3 mr-1" />
        {label}
      </Badge>
    );
  };

  const getConfigTypeBadge = (type: BonusConfig['type']) => {
    const config = {
      META_PERSONAL: { icon: Target, label: 'Meta Personal', className: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400' },
      META_EQUIPO: { icon: Users, label: 'Meta Equipo', className: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400' },
      VIAJE: { icon: Truck, label: 'Por Viaje', className: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400' },
    };
    const { icon: Icon, label, className } = config[type];
    return (
      <Badge className={className}>
        <Icon className="h-3 w-3 mr-1" />
        {label}
      </Badge>
    );
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-display font-bold text-foreground flex items-center gap-2">
            <Zap className="h-6 w-6 text-primary" />
            Bonos Automatizados
          </h1>
          <p className="text-muted-foreground">
            Sistema automático de bonos por metas y viajes
          </p>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        <Card className="shadow-card">
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center">
                <Gift className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Bonos</p>
                <p className="text-2xl font-bold text-foreground">{stats.totalBonuses}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-card">
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-warning/10 flex items-center justify-center">
                <Clock className="h-6 w-6 text-warning" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Pendientes</p>
                <p className="text-2xl font-bold text-foreground">{stats.pendingBonuses}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-card">
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                <CheckCircle className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Aprobados</p>
                <p className="text-2xl font-bold text-foreground">{stats.approvedBonuses}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-card">
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-success/10 flex items-center justify-center">
                <DollarSign className="h-6 w-6 text-success" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Monto Total</p>
                <p className="text-2xl font-bold text-success">S/ {stats.totalAmount.toLocaleString('es-PE')}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-card">
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
                <Settings className="h-6 w-6 text-purple-600" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Reglas Activas</p>
                <p className="text-2xl font-bold text-foreground">{stats.activeConfigs}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full max-w-md grid-cols-2">
          <TabsTrigger value="bonuses" className="flex items-center gap-2">
            <Gift className="h-4 w-4" />
            Bonos Generados
          </TabsTrigger>
          <TabsTrigger value="config" className="flex items-center gap-2">
            <Settings className="h-4 w-4" />
            Configuración
          </TabsTrigger>
        </TabsList>

        {/* Bonuses Tab */}
        <TabsContent value="bonuses" className="space-y-4">
          {/* Filters */}
          <Card className="shadow-card">
            <CardContent className="pt-6">
              <div className="flex gap-2 flex-wrap">
                <Button
                  variant={typeFilter === 'all' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setTypeFilter('all')}
                >
                  Todos
                </Button>
                <Button
                  variant={typeFilter === 'META_PERSONAL' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setTypeFilter('META_PERSONAL')}
                >
                  <Target className="h-4 w-4 mr-1" />
                  Meta Personal
                </Button>
                <Button
                  variant={typeFilter === 'META_EQUIPO' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setTypeFilter('META_EQUIPO')}
                >
                  <Users className="h-4 w-4 mr-1" />
                  Meta Equipo
                </Button>
                <Button
                  variant={typeFilter === 'VIAJE' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setTypeFilter('VIAJE')}
                >
                  <Truck className="h-4 w-4 mr-1" />
                  Por Viaje
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Bonuses Table */}
          <Card className="shadow-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-primary" />
                Bonos Generados Automáticamente
              </CardTitle>
              <CardDescription>
                Los bonos se generan automáticamente cuando se cumplen las condiciones configuradas
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Tipo</TableHead>
                    <TableHead>Nombre</TableHead>
                    <TableHead>Beneficiario</TableHead>
                    <TableHead>Logro</TableHead>
                    <TableHead>Monto</TableHead>
                    <TableHead>Fecha</TableHead>
                    <TableHead>Estado</TableHead>
                    <TableHead>Acciones</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredBonuses.map(bonus => (
                    <TableRow key={bonus.id} className="hover:bg-muted/50">
                      <TableCell>{getTypeBadge(bonus.type)}</TableCell>
                      <TableCell className="font-medium">{bonus.name}</TableCell>
                      <TableCell>
                        {bonus.type === 'META_EQUIPO' ? bonus.teamName : bonus.employeeName}
                      </TableCell>
                      <TableCell>
                        <span className="text-success font-medium">
                          {bonus.achievedValue.toLocaleString('es-PE')} {bonus.thresholdUnit}
                        </span>
                        <span className="text-muted-foreground text-xs block">
                          Meta: {bonus.threshold.toLocaleString('es-PE')} {bonus.thresholdUnit}
                        </span>
                      </TableCell>
                      <TableCell className="font-medium text-success">
                        S/ {bonus.amount.toFixed(2)}
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {format(bonus.date, "dd/MM/yyyy", { locale: es })}
                      </TableCell>
                      <TableCell>{getStatusBadge(bonus.status)}</TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          {bonus.status === 'GENERADO' && (
                            <Button 
                              size="sm" 
                              variant="outline"
                              onClick={() => handleApproveBonus(bonus.id)}
                            >
                              Aprobar
                            </Button>
                          )}
                          {bonus.status === 'APROBADO' && (
                            <Button 
                              size="sm" 
                              className="bg-success hover:bg-success/90"
                              onClick={() => handlePayBonus(bonus.id)}
                            >
                              Pagar
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Configuration Tab */}
        <TabsContent value="config" className="space-y-4">
          <Card className="shadow-card">
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Settings className="h-5 w-5 text-primary" />
                  Configuración de Bonos
                </CardTitle>
                <CardDescription>
                  Configure las reglas y montos para cada tipo de bono automatizado
                </CardDescription>
              </div>
              <Dialog open={isConfigDialogOpen} onOpenChange={(open) => {
                setIsConfigDialogOpen(open);
                if (!open) {
                  setEditingConfig(null);
                  resetConfigForm();
                }
              }}>
                <DialogTrigger asChild>
                  <Button className="bg-gradient-warm hover:opacity-90">
                    <Settings className="h-4 w-4 mr-2" />
                    Nueva Regla
                  </Button>
                </DialogTrigger>
                <DialogContent className="sm:max-w-lg">
                  <DialogHeader>
                    <DialogTitle>
                      {editingConfig ? 'Editar Configuración' : 'Nueva Configuración de Bono'}
                    </DialogTitle>
                    <DialogDescription>
                      Configure las condiciones para generar bonos automáticamente
                    </DialogDescription>
                  </DialogHeader>
                  <div className="grid gap-4 py-4">
                    {!editingConfig && (
                      <div className="space-y-2">
                        <Label>Tipo de Bono</Label>
                        <div className="flex gap-2">
                          <Button
                            type="button"
                            variant={configForm.type === 'META_PERSONAL' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, type: 'META_PERSONAL' }))}
                          >
                            <Target className="h-4 w-4 mr-1" />
                            Meta Personal
                          </Button>
                          <Button
                            type="button"
                            variant={configForm.type === 'META_EQUIPO' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, type: 'META_EQUIPO' }))}
                          >
                            <Users className="h-4 w-4 mr-1" />
                            Meta Equipo
                          </Button>
                          <Button
                            type="button"
                            variant={configForm.type === 'VIAJE' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, type: 'VIAJE' }))}
                          >
                            <Truck className="h-4 w-4 mr-1" />
                            Por Viaje
                          </Button>
                        </div>
                      </div>
                    )}

                    <div className="space-y-2">
                      <Label>Nombre del Bono</Label>
                      <Input 
                        placeholder="Ej: Bono por Meta de Ventas"
                        value={configForm.name}
                        onChange={(e) => setConfigForm(prev => ({ ...prev, name: e.target.value }))}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label>Descripción</Label>
                      <Input 
                        placeholder="Descripción de las condiciones"
                        value={configForm.description}
                        onChange={(e) => setConfigForm(prev => ({ ...prev, description: e.target.value }))}
                      />
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Meta a Alcanzar</Label>
                        <Input 
                          type="number"
                          placeholder="10000"
                          value={configForm.threshold}
                          onChange={(e) => setConfigForm(prev => ({ ...prev, threshold: e.target.value }))}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Unidad</Label>
                        <div className="flex gap-1">
                          <Button
                            type="button"
                            variant={configForm.thresholdUnit === 'soles' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, thresholdUnit: 'soles' }))}
                          >
                            Soles
                          </Button>
                          <Button
                            type="button"
                            variant={configForm.thresholdUnit === '%' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, thresholdUnit: '%' }))}
                          >
                            %
                          </Button>
                          <Button
                            type="button"
                            variant={configForm.thresholdUnit === 'viajes' ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setConfigForm(prev => ({ ...prev, thresholdUnit: 'viajes' }))}
                          >
                            Viajes
                          </Button>
                        </div>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label>Monto del Bono (S/)</Label>
                      <Input 
                        type="number"
                        placeholder="200"
                        value={configForm.amount}
                        onChange={(e) => setConfigForm(prev => ({ ...prev, amount: e.target.value }))}
                      />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => {
                      setIsConfigDialogOpen(false);
                      setEditingConfig(null);
                      resetConfigForm();
                    }}>
                      Cancelar
                    </Button>
                    <Button className="bg-gradient-warm hover:opacity-90" onClick={handleSaveConfig}>
                      {editingConfig ? 'Guardar Cambios' : 'Crear Regla'}
                    </Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {['META_PERSONAL', 'META_EQUIPO', 'VIAJE'].map(type => {
                  const typeConfigs = bonusConfigs.filter(c => c.type === type);
                  if (typeConfigs.length === 0) return null;
                  
                  return (
                    <div key={type} className="space-y-3">
                      <h3 className="font-semibold flex items-center gap-2">
                        {type === 'META_PERSONAL' && <Target className="h-4 w-4 text-blue-600" />}
                        {type === 'META_EQUIPO' && <Users className="h-4 w-4 text-purple-600" />}
                        {type === 'VIAJE' && <Truck className="h-4 w-4 text-orange-600" />}
                        {type === 'META_PERSONAL' && 'Bonos por Meta Personal'}
                        {type === 'META_EQUIPO' && 'Bonos por Meta de Equipo'}
                        {type === 'VIAJE' && 'Bonos por Viaje'}
                      </h3>
                      <div className="grid gap-3">
                        {typeConfigs.map(config => (
                          <Card key={config.id} className={`border ${config.isActive ? 'border-success/30' : 'border-muted'}`}>
                            <CardContent className="pt-4">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                  <Switch 
                                    checked={config.isActive}
                                    onCheckedChange={() => handleToggleConfig(config.id)}
                                  />
                                  <div>
                                    <p className="font-medium">{config.name}</p>
                                    <p className="text-sm text-muted-foreground">{config.description}</p>
                                  </div>
                                </div>
                                <div className="flex items-center gap-4">
                                  <div className="text-right">
                                    <p className="text-sm text-muted-foreground">Meta</p>
                                    <p className="font-medium">
                                      {config.threshold.toLocaleString('es-PE')} {config.thresholdUnit}
                                    </p>
                                  </div>
                                  <div className="text-right">
                                    <p className="text-sm text-muted-foreground">Monto</p>
                                    <p className="font-bold text-success">S/ {config.amount}</p>
                                  </div>
                                  <Button 
                                    variant="outline" 
                                    size="sm"
                                    onClick={() => handleEditConfig(config)}
                                  >
                                    Editar
                                  </Button>
                                </div>
                              </div>
                            </CardContent>
                          </Card>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default EmployeeBonuses;
